### ISSUE TITLE
Investigate failing tests

### ISSUE THREAD

**Issue by eloekset** [SharpRepository/SharpRepository#159]
CI builds fail because 24 tests fail. Even some of the unit tests fail when run locally on a dev machine.
<img width="267" alt="2016-08-03_20-57-39" src="https://cloud.githubusercontent.com/assets/791721/17412215/dff2db48-5a7b-11e6-8025-0f80e0d999b7.png">

**Comment by eloekset** [comment]
Turns out all the failing tests in the image above have the same root cause, so instead of creating several issues, I copy the content from #160 in here and close that issue.

### CompoundKeyRepositoryDeleteTests.cs
```
~\SharpRepository.Tests.Integration\CompoundKeyRepositoryDeleteTests.cs : line 16
Result1 StackTrace:	
at SharpRepository.Repository.CompoundKeyRepositoryBase`3.GetAll(IQueryOptions`1 queryOptions, IFetchStrategy`1 fetchStrategy) in ~\SharpRepository.Repository\CompoundKeyRepositoryBase.cs:line 682
at SharpRepository.Repository.CompoundKeyRepositoryBase`3.GetAll() in ~\SharpRepository.Repository\CompoundKeyRepositoryBase.cs:line 653
at SharpRepository.Tests.Integration.CompoundKeyRepositoryDeleteTests.Delete_Should_Remove_Multiple_Items(ICompoundKeyRepository`3 repository) in ~\SharpRepository.Tests.Integration\CompoundKeyRepositoryDeleteTests.cs:line 77
Result1 Message:	System.NotImplementedException : The method or operation is not implemented.
```

### CompoundKeyRepositoryAddTests.cs
```
~\SharpRepository.Tests.Integration\CompoundKeyRepositoryAddTests.cs : line 25
Result1 StackTrace:	
at SharpRepository.Repository.CompoundKeyRepositoryBase`3.GetAll(IQueryOptions`1 queryOptions, IFetchStrategy`1 fetchStrategy) in ~\SharpRepository.Repository\CompoundKeyRepositoryBase.cs:line 682
at SharpRepository.Repository.CompoundKeyRepositoryBase`3.GetAll() in ~\SharpRepository.Repository\CompoundKeyRepositoryBase.cs:line 653
at SharpRepository.Tests.Integration.CompoundKeyRepositoryAddTests.Add_InBatchMode_Should_Delay_The_Action(ICompoundKeyRepository`3 repository) in ~\SharpRepository.Tests.Integration\CompoundKeyRepositoryAddTests.cs:line 30
Result1 Message:	System.NotImplementedException : The method or operation is not implemented.
Result2 StackTrace:	
at SharpRepository.Repository.CompoundKeyRepositoryBase`3.GetAll(IQueryOptions`1 queryOptions, IFetchStrategy`1 fetchStrategy) in ~\SharpRepository.Repository\CompoundKeyRepositoryBase.cs:line 682
at SharpRepository.Repository.CompoundKeyRepositoryBase`3.GetAll() in ~\SharpRepository.Repository\CompoundKeyRepositoryBase.cs:line 653
at SharpRepository.Tests.Integration.CompoundKeyRepositoryAddTests.Add_Should_Result_In_Proper_Total_Items(ICompoundKeyRepository`3 repository) in ~\SharpRepository.Tests.Integration\CompoundKeyRepositoryAddTests.cs:line 19
Result2 Message:	System.NotImplementedException : The method or operation is not implemented.
```

### CompoundKeyRepositoryUpdateTests.cs
Same cause as above
```
SharpRepository.Tests.Integration.CompoundKeyRepositoryUpdateTests.Update_Should_Update_Multiple_Items(ICompoundKeyRepository`3 repository) in ~\SharpRepository.Tests.Integration\CompoundKeyRepositoryUpdateTests.cs:line 45
Result1 Message:	System.NotImplementedException : The method or operation is not implemented.
```

### CompoundKeyRepositoryGetAllTests.cs
Same cause as above
```
SharpRepository.Tests.Integration.CompoundKeyRepositoryGetAllTests.GetAll_Should_Return_Every_Item(ICompoundKeyRepository`3 repository) in ~\SharpRepository.Tests.Integration\CompoundKeyRepositoryGetAllTests.cs:line 23
Result1 Message:	System.NotImplementedException : The method or operation is not implemented.
 SharpRepository.Tests.Integration.CompoundKeyRepositoryGetAllTests.GetAll_With_Anonymous_Selector_Should_Return_Every_Item(ICompoundKeyRepository`3 repository) in ~\SharpRepository.Tests.Integration\CompoundKeyRepositoryGetAllTests.cs:line 67
Result2 Message:	System.NotImplementedException : The method or operation is not implemented.
 SharpRepository.Tests.Integration.CompoundKeyRepositoryGetAllTests.GetAll_With_Selector_Should_Return_Every_Item(ICompoundKeyRepository`3 repository) in ~\SharpRepository.Tests.Integration\CompoundKeyRepositoryGetAllTests.cs:line 55
Result3 Message:	System.NotImplementedException : The method or operation is not implemented.
```

All these four tests fail because this method in `CompoundKeyRepositoryBase<T, TKey, TKey2>` isn't implemented:
```
public IEnumerable<T> GetAll(IQueryOptions<T> queryOptions, IFetchStrategy<T> fetchStrategy)
{
    throw new NotImplementedException();
}
```

Several other methods in that class throw NotImplementedException as well.

**Comment by omarpiani** [comment]
develop branch is not updated... all the last commits/PR are in an outdated branch

**Comment by eloekset** [comment]
develop is the default branch, but you're right - it's not in sync with the master branch.
![2016-10-18_1312](https://cloud.githubusercontent.com/assets/791721/19475477/a7d96922-9534-11e6-9860-ea77d6524c87.png)
![2016-10-18_1313](https://cloud.githubusercontent.com/assets/791721/19475483/ad3c67d4-9534-11e6-9596-ac3f44b90880.png)

**Comment by omarpiani** [comment]
Now develop is in sync
