### ISSUE TITLE
InMemoryRepository test fails

### ISSUE THREAD

**Issue by eloekset** [SharpRepository/SharpRepository#160]
Related to #159 
### CompoundKeyRepositoryDeleteTests.cs
```
~\SharpRepository.Tests.Integration\CompoundKeyRepositoryDeleteTests.cs : line 16
Result1 StackTrace:	
at SharpRepository.Repository.CompoundKeyRepositoryBase`3.GetAll(IQueryOptions`1 queryOptions, IFetchStrategy`1 fetchStrategy) in ~\SharpRepository.Repository\CompoundKeyRepositoryBase.cs:line 682
at SharpRepository.Repository.CompoundKeyRepositoryBase`3.GetAll() in ~\SharpRepository.Repository\CompoundKeyRepositoryBase.cs:line 653
at SharpRepository.Tests.Integration.CompoundKeyRepositoryDeleteTests.Delete_Should_Remove_Multiple_Items(ICompoundKeyRepository`3 repository) in ~\SharpRepository.Tests.Integration\CompoundKeyRepositoryDeleteTests.cs:line 77
Result1 Message:	System.NotImplementedException : The method or operation is not implemented.
```

### CompoundKeyRepositoryAddTests.cs
```
~\SharpRepository.Tests.Integration\CompoundKeyRepositoryAddTests.cs : line 25
Result1 StackTrace:	
at SharpRepository.Repository.CompoundKeyRepositoryBase`3.GetAll(IQueryOptions`1 queryOptions, IFetchStrategy`1 fetchStrategy) in ~\SharpRepository.Repository\CompoundKeyRepositoryBase.cs:line 682
at SharpRepository.Repository.CompoundKeyRepositoryBase`3.GetAll() in ~\SharpRepository.Repository\CompoundKeyRepositoryBase.cs:line 653
at SharpRepository.Tests.Integration.CompoundKeyRepositoryAddTests.Add_InBatchMode_Should_Delay_The_Action(ICompoundKeyRepository`3 repository) in ~\SharpRepository.Tests.Integration\CompoundKeyRepositoryAddTests.cs:line 30
Result1 Message:	System.NotImplementedException : The method or operation is not implemented.
Result2 StackTrace:	
at SharpRepository.Repository.CompoundKeyRepositoryBase`3.GetAll(IQueryOptions`1 queryOptions, IFetchStrategy`1 fetchStrategy) in ~\SharpRepository.Repository\CompoundKeyRepositoryBase.cs:line 682
at SharpRepository.Repository.CompoundKeyRepositoryBase`3.GetAll() in ~\SharpRepository.Repository\CompoundKeyRepositoryBase.cs:line 653
at SharpRepository.Tests.Integration.CompoundKeyRepositoryAddTests.Add_Should_Result_In_Proper_Total_Items(ICompoundKeyRepository`3 repository) in ~\SharpRepository.Tests.Integration\CompoundKeyRepositoryAddTests.cs:line 19
Result2 Message:	System.NotImplementedException : The method or operation is not implemented.
```

### CompoundKeyRepositoryUpdateTests.cs
Same cause as above
```
SharpRepository.Tests.Integration.CompoundKeyRepositoryUpdateTests.Update_Should_Update_Multiple_Items(ICompoundKeyRepository`3 repository) in ~\SharpRepository.Tests.Integration\CompoundKeyRepositoryUpdateTests.cs:line 45
Result1 Message:	System.NotImplementedException : The method or operation is not implemented.
```

### CompoundKeyRepositoryGetAllTests.cs
Same cause as above
```
SharpRepository.Tests.Integration.CompoundKeyRepositoryGetAllTests.GetAll_Should_Return_Every_Item(ICompoundKeyRepository`3 repository) in ~\SharpRepository.Tests.Integration\CompoundKeyRepositoryGetAllTests.cs:line 23
Result1 Message:	System.NotImplementedException : The method or operation is not implemented.
 SharpRepository.Tests.Integration.CompoundKeyRepositoryGetAllTests.GetAll_With_Anonymous_Selector_Should_Return_Every_Item(ICompoundKeyRepository`3 repository) in ~\SharpRepository.Tests.Integration\CompoundKeyRepositoryGetAllTests.cs:line 67
Result2 Message:	System.NotImplementedException : The method or operation is not implemented.
 SharpRepository.Tests.Integration.CompoundKeyRepositoryGetAllTests.GetAll_With_Selector_Should_Return_Every_Item(ICompoundKeyRepository`3 repository) in ~\SharpRepository.Tests.Integration\CompoundKeyRepositoryGetAllTests.cs:line 55
Result3 Message:	System.NotImplementedException : The method or operation is not implemented.
```

All these four tests fail because this method in `CompoundKeyRepositoryBase<T, TKey, TKey2>` isn't implemented:
```
public IEnumerable<T> GetAll(IQueryOptions<T> queryOptions, IFetchStrategy<T> fetchStrategy)
{
    throw new NotImplementedException();
}
```

Several other methods in that class throw NotImplementedException as well.

**Comment by eloekset** [comment]
Closing this issue. See #159
