### ISSUE TITLE
Sample CoreMVC with MongoDB doesn't work

### ISSUE THREAD

**Issue by tresoldigiorgio** [SharpRepository/SharpRepository#194]
I've tried to use the sample CoreMVC with MongoDb but when i insert an email address it throw an exception like this

System.ArgumentException
  HResult=0x80070057
  Message=.NET type SharpRepository.CoreMvc.Models.Email cannot be mapped to a BsonValue.
  Source=MongoDB.Bson
  StackTrace:
   at MongoDB.Bson.BsonTypeMapper.MapToBsonValue(Object value)
   at MongoDB.Bson.BsonArray.AddRange(IEnumerable values)
   at MongoDB.Bson.BsonTypeMapper.MapToBsonValue(Object value, BsonType bsonType)
   at SharpRepository.MongoDbRepository.MongoDbRepositoryBase`2.GetMongoProperty(T entity, String propertyName) in C:\Users\GiorgioTresoldi\Downloads\SharpRepository-develop\SharpRepository.MongoDbRepository\MongoDbRepositoryBase.cs:line 359
   at SharpRepository.MongoDbRepository.MongoDbRepositoryBase`2.UpdateItem(T entity) in C:\Users\GiorgioTresoldi\Downloads\SharpRepository-develop\SharpRepository.MongoDbRepository\MongoDbRepositoryBase.cs:line 338
   at SharpRepository.Repository.RepositoryBase`2.ProcessUpdate(T entity, Boolean batchMode) in C:\Users\GiorgioTresoldi\Downloads\SharpRepository-develop\SharpRepository.Repository\RepositoryBase.cs:line 1556
   at SharpRepository.Repository.RepositoryBase`2.Update(T entity) in C:\Users\GiorgioTresoldi\Downloads\SharpRepository-develop\SharpRepository.Repository\RepositoryBase.cs:line 1546
   at SharpRepository.CoreMvc.Controllers.EmailsController.Create(Email email) in C:\Users\GiorgioTresoldi\Downloads\SharpRepository-develop\SharpRepository.Samples.CoreMvc\Controllers\EmailsController.cs:line 47
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()

I've only modified the mongodb connectionstring and here is my Cofigureservice
`public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();

            //services.AddDbContext<ContactContext>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")), ServiceLifetime.Transient);

            // services.AddTransient<DbContext, ContactContext>(); // needed if you don't write dbContextClass on json configuration

            services.AddTransient<EmailRepository>(r => new EmailRepository(RepositoryFactory.BuildSharpRepositoryConfiguation(Configuration.GetSection("sharpRepository"))));

            // return services.UseSharpRepository(Configuration.GetSection("sharpRepository")); //default InMemory
            return services.UseSharpRepository(Configuration.GetSection("sharpRepository"), "mongoDb"); // for Mongo Db
            //return services.UseSharpRepository(Configuration.GetSection("sharpRepository"), "efCore"); // for Ef Core
        }`

**Comment by omarpiani** [comment]
effectivelly at the moment MongoBbRepository seams not to support Mongo relation with other classes.
I'll keep studing. 

Atm I can't make it work using plain MongoDb.Driver code.

Someone can get it work?

```
database.GetCollection<Contact>("Contact").ReplaceOneAsync<Contact>(
                 c => c.Id == contactId,
                 contact
                 );
```
i tried with something like that

**Comment by tresoldigiorgio** [comment]
I've modified the Update method in MongoDbRepositoryBase and it works

` protected override void UpdateItem(T entity)
        {
            TKey pkValue;
            GetPrimaryKey(entity, out pkValue);
            if (IsValidKey(pkValue))
            {
                var keyMap = BsonClassMap.LookupClassMap(typeof(T)).IdMemberMap;
                var keyPropertyName = keyMap.MemberName;
                var keyBsonType = ((StringSerializer)keyMap.GetSerializer()).Representation;
                var keyBsonPropertyValue = BsonTypeMapper.MapToBsonValue(pkValue, keyBsonType);
                var keyPair = new KeyValuePair<string, BsonValue>(keyPropertyName, keyBsonPropertyValue);
                var filter = Builders<T>.Filter.Eq(keyPair.Key, keyPair.Value);

                BaseCollection().ReplaceOne(filter, entity);

                //var bsonMembers = BsonClassMap.LookupClassMap(typeof(T)).AllMemberMaps.Where(m => m.MemberName != keyPropertyName);
                //var updates = new List<UpdateDefinition<T>>();
                //foreach (var members in bsonMembers)
                //{
                //    var propPair = GetMongoProperty(entity, members.MemberName);
                //    updates.Add(Builders<T>.Update.Set(propPair.Key, propPair.Value));
                //}

                //BaseCollection().UpdateOne(filter, Builders<T>.Update.Combine(updates));
            }

        }`

**Comment by tresoldigiorgio** [comment]
protected override void UpdateItem(T entity)
        {

            TKey pkValue;
            GetPrimaryKey(entity, out pkValue);
            if (IsValidKey(pkValue))
            {

                var keyMap = BsonClassMap.LookupClassMap(typeof(T)).IdMemberMap;
                var keyPropertyName = keyMap.MemberName;
                var keyBsonType = ((StringSerializer)keyMap.GetSerializer()).Representation;
                var keyBsonPropertyValue = BsonTypeMapper.MapToBsonValue(pkValue, keyBsonType);
                var keyPair = new KeyValuePair<string, BsonValue>(keyPropertyName, keyBsonPropertyValue);
                var filter = Builders<T>.Filter.Eq(keyPair.Key, keyPair.Value);

                BaseCollection().ReplaceOne(filter, entity);

            }

        }

It works

**Comment by omarpiani** [comment]
Great job! 
I released new package with your edits SharpRepository.MongoDbRepository.2.0.3-beta1
