### ISSUE TITLE
MongoDbRepository needs to be update mongodb driver references

### ISSUE THREAD

**Issue by pareshjoshi** [SharpRepository/SharpRepository#247]
I am currently working on .NET Core 3.0 application and using mongodb repository. However, call to following fails:

`new MongoDbRepository<Contact, int>("mongodb://localhost:27017/contacts")
`
with an exception:

```
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'MongoDB.Bson.Serialization.BsonClassMap' threw an exception.
  Source=MongoDB.Bson
  StackTrace:
   at MongoDB.Bson.Serialization.BsonClassMap.IsClassMapRegistered(Type type)
   at SharpRepository.MongoDbRepository.MongoDbRepositoryBase`2.Initialize(IMongoDatabase mongoDatabase)
   at SharpRepository.MongoDbRepository.MongoDbRepositoryBase`2..ctor(String connectionString, ICachingStrategy`2 cachingStrategy, SslSettings sslSettings)
   at SharpRepository.MongoDbRepository.MongoDbRepository`2..ctor(String connectionString, ICachingStrategy`2 cachingStrategy)
   at ContactsService.Startup.ConfigureServices(IServiceCollection services) in C:\Projects\pycapp\Contacts\ContactsService\Startup.cs:line 26
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass15_0.<BuildStartupServicesFilterPipeline>g__RunPipeline|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass14_0.<ConfigureServices>g__ConfigureServicesWithContainerConfiguration|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)

Inner Exception 1:
ArgumentNullException: Value cannot be null. (Parameter 'type')

```

Posts on internet suggests this is an issue with mongodb driver and has been fixed in 2.8.x.

**Comment by omarpiani** [comment]
And updating your local driver does not resolves?

**Comment by omarpiani** [comment]
https://jira.mongodb.org/browse/CSHARP-2595

I released MongoDbRepository.2.1.0-prerelease  with mongo 2.8.1 required.

Thanks


Il giorno gio 7 nov 2019 alle ore 14:00 Atman <notifications@github.com> ha
scritto:

**Comment by pareshjoshi** [comment]
ok , I will test the latest packages and let you know

**Comment by omarpiani** [comment]
released as stable
